import { create } from "zustand";
import { persist } from "zustand/middleware";

export type Language = "vi" | "en";

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  vi: {
    "nav.home": "Trang chủ",
    "nav.mods": "Bản Mod",
    "nav.dex": "FusionDex",
    "nav.videos": "Videos",
    "nav.admin": "Quản trị",
    "nav.login": "Đăng nhập",
    "nav.logout": "Đăng xuất",
    "nav.categories": "Danh Mục",
    "hero.title": "PvZ Fusion Hub",
    "hero.subtitle": "Khám phá thế giới thực vật và thây ma kết hợp độc đáo nhất. Wiki tổng hợp mod, công thức và hướng dẫn.",
    "hero.cta.mods": "Khám phá Mod",
    "hero.cta.dex": "Mở FusionDex",
    "common.loading": "Đang tải...",
    "common.error": "Đã xảy ra lỗi.",
    "common.retry": "Thử lại",
    "common.download": "Tải xuống",
    "common.close": "Đóng",
    "mods.title": "Kho lưu trữ Mod",
    "mods.subtitle": "Duyệt các phiên bản, đọc changelog và tải tệp mới nhất.",
    "mods.search": "Tìm kiếm bản mod...",
    "dex.title": "Khám phá Fusion",
    "dex.subtitle": "Danh sách công thức và kỹ năng fusion được tuyển chọn.",
    "dex.search": "Tìm kiếm fusion...",
    "dex.filter.all": "Tất cả",
    "dex.filter.plant": "Cây",
    "dex.filter.zombie": "Zombie",
    "videos.title": "Video Fusion",
    "videos.subtitle": "Các link YouTube được tuyển chọn kèm ảnh thu nhỏ.",
    "videos.search": "Tìm kiếm video...",
    "admin.title": "Bảng Điều Khiển",
    "admin.subtitle": "Quản lý dữ liệu hệ thống.",
    "login.title": "Đăng Nhập",
    "login.subtitle": "Chào mừng trở lại PvZ Fusion Hub",
    "login.email": "Email",
    "login.password": "Mật khẩu",
    "login.submit": "Đăng nhập",
    "login.no_account": "Chưa có tài khoản?",
    "login.register_link": "Đăng ký tại đây",
    "register.title": "Tạo Tài Khoản",
    "register.subtitle": "Tham gia cộng đồng PvZ Fusion",
    "register.username": "Tên đăng nhập",
    "register.email": "Email",
    "register.password": "Mật khẩu",
    "register.submit": "Đăng ký",
    "register.have_account": "Đã có tài khoản?",
    "register.login_link": "Đăng nhập tại đây",
    "home.mods_title": "KHO LƯU TRỮ MOD",
    "home.mods_view_all": "Xem tất cả mod",
    "home.fusions_title": "FUSION NỔI BẬT",
    "home.fusions_view_all": "Xem FusionDex",
    "home.videos_title": "VIDEO MỚI NHẤT",
    "home.videos_view_all": "Xem tất cả video",
    "category.no_items": "Danh mục trống",
    "category.no_items_desc": "Chưa có nội dung nào trong danh mục này.",
  },
  en: {
    "nav.home": "Home",
    "nav.mods": "Mods",
    "nav.dex": "FusionDex",
    "nav.videos": "Videos",
    "nav.admin": "Admin",
    "nav.login": "Login",
    "nav.logout": "Logout",
    "nav.categories": "Categories",
    "hero.title": "PvZ Fusion Hub",
    "hero.subtitle": "Discover the ultimate combined world of plants and zombies. Your wiki for mods, recipes, and guides.",
    "hero.cta.mods": "Explore Mods",
    "hero.cta.dex": "Open FusionDex",
    "common.loading": "Loading...",
    "common.error": "An error occurred.",
    "common.retry": "Retry",
    "common.download": "Download",
    "common.close": "Close",
    "mods.title": "Mod Archive",
    "mods.subtitle": "Browse versions, read changelogs, and download files.",
    "mods.search": "Search mods...",
    "dex.title": "Fusion Explorer",
    "dex.subtitle": "Curated list of fusion recipes and abilities.",
    "dex.search": "Search fusions...",
    "dex.filter.all": "All",
    "dex.filter.plant": "Plant",
    "dex.filter.zombie": "Zombie",
    "videos.title": "Fusion Videos",
    "videos.subtitle": "Curated YouTube videos and gameplay showcases.",
    "videos.search": "Search videos...",
    "admin.title": "Dashboard",
    "admin.subtitle": "Manage system data.",
    "login.title": "Sign In",
    "login.subtitle": "Welcome back to PvZ Fusion Hub",
    "login.email": "Email",
    "login.password": "Password",
    "login.submit": "Sign In",
    "login.no_account": "Don't have an account?",
    "login.register_link": "Register here",
    "register.title": "Create Account",
    "register.subtitle": "Join the PvZ Fusion community",
    "register.username": "Username",
    "register.email": "Email",
    "register.password": "Password",
    "register.submit": "Register",
    "register.have_account": "Already have an account?",
    "register.login_link": "Login here",
    "home.mods_title": "MOD ARCHIVE",
    "home.mods_view_all": "View all mods",
    "home.fusions_title": "FEATURED FUSIONS",
    "home.fusions_view_all": "Open FusionDex",
    "home.videos_title": "LATEST VIDEOS",
    "home.videos_view_all": "View all videos",
    "category.no_items": "Empty Category",
    "category.no_items_desc": "No content in this category yet.",
  }
};

export const useLanguage = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: "vi",
      setLanguage: (lang) => set({ language: lang }),
      t: (key) => translations[get().language][key] || key,
    }),
    {
      name: "pvz-language",
    }
  )
);
